workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    environment:
      flutter: stable
      groups:
        - google_play
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
